<?php

namespace Zoolok\IpBlocker\Tests\Services;

use PHPUnit\Framework\TestCase;
use Zoolok\IpBlocker\Services\DenyGenerator;

class DenyGeneratorTest extends TestCase
{
    private string $tempDir;

    protected function setUp(): void
    {
        $this->tempDir = sys_get_temp_dir().'/ip-blocker-test-'.uniqid();
        mkdir($this->tempDir, 0777, true);
    }

    protected function tearDown(): void
    {
        $this->removeDirectory($this->tempDir);
    }

    public function test_generates_nginx_config_with_single_ip(): void
    {
        $denyPath = $this->tempDir.'/blocked-ips.conf';

        $generator = new DenyGenerator(
            serverType: 'nginx',
            denyPath: $denyPath,
            reloadCommand: 'echo reloaded',
        );

        $result = $generator->generate(['192.168.1.1']);

        $this->assertTrue($result);
        $this->assertFileExists($denyPath);

        $content = file_get_contents($denyPath);

        $this->assertStringContainsString('deny 192.168.1.1;', $content);
        $this->assertStringContainsString('# Auto-generated by laravel-ip-blocker', $content);
    }

    public function test_generates_nginx_config_with_multiple_ips(): void
    {
        $denyPath = $this->tempDir.'/blocked-ips.conf';

        $generator = new DenyGenerator(
            serverType: 'nginx',
            denyPath: $denyPath,
            reloadCommand: 'echo reloaded',
        );

        $result = $generator->generate(['10.0.0.1', '192.168.1.1', '::1']);

        $this->assertTrue($result);

        $content = file_get_contents($denyPath);

        $this->assertStringContainsString('deny 10.0.0.1;', $content);
        $this->assertStringContainsString('deny 192.168.1.1;', $content);
        $this->assertStringContainsString('deny ::1;', $content);
    }

    public function test_generates_apache_config(): void
    {
        $htaccessPath = $this->tempDir.'/.htaccess';

        $generator = new DenyGenerator(
            serverType: 'apache',
            denyPath: '/unused',
            reloadCommand: 'echo reloaded',
            allowOverridePath: $htaccessPath,
        );

        $result = $generator->generate(['10.0.0.1', '192.168.1.1']);

        $this->assertTrue($result);
        $this->assertFileExists($htaccessPath);

        $content = file_get_contents($htaccessPath);

        $this->assertStringContainsString('Require not ip 10.0.0.1', $content);
        $this->assertStringContainsString('Require not ip 192.168.1.1', $content);
        $this->assertStringContainsString('<Limit GET POST PUT PATCH DELETE>', $content);
        $this->assertStringContainsString('</Limit>', $content);
    }

    public function test_generates_header_only_for_empty_ips(): void
    {
        $denyPath = $this->tempDir.'/blocked-ips.conf';

        $generator = new DenyGenerator(
            serverType: 'nginx',
            denyPath: $denyPath,
            reloadCommand: 'echo reloaded',
        );

        $result = $generator->generate([]);

        $this->assertTrue($result);

        $content = file_get_contents($denyPath);

        $this->assertStringContainsString('# Auto-generated by laravel-ip-blocker', $content);
        $this->assertStringNotContainsString('deny ;', $content);
    }

    public function test_skips_invalid_ips_when_generating_config(): void
    {
        $denyPath = $this->tempDir.'/blocked-ips.conf';

        $generator = new DenyGenerator(
            serverType: 'nginx',
            denyPath: $denyPath,
            reloadCommand: 'echo reloaded',
        );

        $result = $generator->generate([
            '10.0.0.1',
            'not-an-ip',
            '192.168.1.1; include /etc/passwd;',
            '::1',
        ]);

        $this->assertTrue($result);

        $content = file_get_contents($denyPath);

        $this->assertStringContainsString('deny 10.0.0.1;', $content);
        $this->assertStringContainsString('deny ::1;', $content);
        $this->assertStringNotContainsString('not-an-ip', $content);
        $this->assertStringNotContainsString('include /etc/passwd', $content);
    }

    public function test_creates_directory_and_writes_config(): void
    {
        $nestedPath = $this->tempDir.'/deeply/nested/config/blocked-ips.conf';

        $generator = new DenyGenerator(
            serverType: 'nginx',
            denyPath: $nestedPath,
            reloadCommand: 'echo reloaded',
        );

        $result = $generator->generate(['10.0.0.1']);

        $this->assertTrue($result);
        $this->assertFileExists($nestedPath);
    }

    private function removeDirectory(string $dir): void
    {
        if (! is_dir($dir)) {
            return;
        }

        $files = array_diff(scandir($dir) ?: [], ['.', '..']);

        foreach ($files as $file) {
            $filePath = $dir.'/'.$file;

            if (is_file($filePath)) {
                unlink($filePath);
            } else {
                $this->removeDirectory($filePath);
            }
        }

        rmdir($dir);
    }
}
