<?php

namespace Zoolok\IpBlocker\Services;

use Psr\Log\LoggerInterface;
use Psr\Log\NullLogger;
use Zoolok\IpBlocker\Models\BlockedIp;

class DenyGenerator
{
    private const HEADER = '# Auto-generated by laravel-ip-blocker. Do not edit manually.';

    /**
     * @param string $serverType Web server type: 'nginx' or 'apache'.
     * @param string $denyPath Target path for the nginx deny config file.
     * @param string $reloadCommand Shell command used to reload the web server.
     * @param string $allowOverridePath Target path for the Apache .htaccess file.
     * @param LoggerInterface $logger PSR-3 logger; used only for error reporting.
     */
    public function __construct(
        private readonly string $serverType = 'nginx',
        private readonly string $denyPath = '/etc/nginx/conf.d/blocked-ips.conf',
        private readonly string $reloadCommand = 'nginx -s reload',
        private readonly string $allowOverridePath = '/var/www/html/.htaccess',
        private readonly LoggerInterface $logger = new NullLogger(),
    ) {}

    /**
     * Regenerate the deny config from all currently active blocks in the
     * blocked_ips table.
     *
     * The generated file always mirrors the database: it contains every IP
     * whose block is active (is_active = true and, if set, not yet expired)
     * and drops IPs whose block was removed or has already expired. This keeps
     * the config in sync with the table on every add, edit or delete.
     *
     * @return bool True on success, false on failure.
     */
    public function syncFromDatabase(): bool
    {
        $ips = BlockedIp::active()->pluck('ip')->all();

        return $this->generate($ips);
    }

    /**
     * Generate a deny configuration for the web server.
     *
     * Deduplicates, validates and sorts the IP list, writes the appropriate
     * nginx or Apache config file (creating the target directory when
     * needed) and reloads the web server. Invalid IP addresses are skipped.
     *
     * @param array<int, string> $ips List of IP addresses to block.
     * @return bool True on success, false on failure.
     */
    public function generate(array $ips): bool
    {
        $uniqueIps = array_values(array_unique(array_filter(
            $ips,
            fn (string $ip): bool => $this->isValidIp($ip),
        )));

        sort($uniqueIps);

        $content = $this->serverType === 'nginx'
            ? $this->generateNginxConfig($uniqueIps)
            : $this->generateApacheConfig($uniqueIps);

        $targetPath = $this->serverType === 'nginx' ? $this->denyPath : $this->allowOverridePath;

        try {
            $dir = dirname($targetPath);
            if (! is_dir($dir)) {
                mkdir($dir, 0755, true);
            }

            $written = file_put_contents($targetPath, $content, LOCK_EX);

            if ($written === false) {
                $this->logger->error('[DenyGenerator.generate] Failed to write config file', [
                    'path' => $targetPath,
                ]);

                return false;
            }

            return $this->reloadServer();
        } catch (\Throwable $e) {
            $this->logger->error('[DenyGenerator.generate] Error generating config', [
                'path' => $targetPath,
                'error' => $e->getMessage(),
            ]);

            return false;
        }
    }

    /**
     * Check whether a string is a valid IPv4 or IPv6 address.
     *
     * @param string $ip Candidate IP address.
     * @return bool True when the string is a valid IP address.
     */
    private function isValidIp(string $ip): bool
    {
        return filter_var($ip, FILTER_VALIDATE_IP) !== false;
    }

    /**
     * Reload the web server by executing the configured command.
     *
     * The command is escaped to prevent shell injection from a malicious
     * configuration value.
     *
     * @return bool True when the command exited with code 0.
     */
    private function reloadServer(): bool
    {
        $output = [];
        $exitCode = 0;

        exec(escapeshellcmd($this->reloadCommand), $output, $exitCode);

        if ($exitCode !== 0) {
            $this->logger->error('[DenyGenerator.reloadServer] Server reload failed', [
                'exit_code' => $exitCode,
                'output' => implode("\n", $output),
            ]);
        }

        return $exitCode === 0;
    }

    /**
     * Generate nginx deny configuration content.
     *
     * @param array<int, string> $ips Unique, sorted IP addresses to block.
     * @return string Config file content.
     */
    private function generateNginxConfig(array $ips): string
    {
        $lines = [
            self::HEADER,
            '# Generated: '.now()->toIso8601String(),
            "# Total blocked IPs: ".count($ips),
            '',
        ];

        foreach ($ips as $ip) {
            $lines[] = "deny {$ip};";
        }

        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * Generate Apache deny configuration content (.htaccess or conf).
     *
     * @param array<int, string> $ips Unique, sorted IP addresses to block.
     * @return string Config file content.
     */
    private function generateApacheConfig(array $ips): string
    {
        $lines = [
            self::HEADER,
            '# Generated: '.now()->toIso8601String(),
            "# Total blocked IPs: ".count($ips),
            '',
            '<Limit GET POST PUT PATCH DELETE>',
        ];

        foreach ($ips as $ip) {
            $lines[] = "    Require not ip {$ip}";
        }

        $lines[] = '</Limit>';
        $lines[] = '';

        return implode("\n", $lines);
    }
}
