<?php

namespace Zoolok\IpBlocker\Services;

use Illuminate\Support\Facades\Log;
use Zoolok\IpBlocker\Models\BlockedIp;

class DenyGenerator
{
    private const string HEADER = '# Auto-generated by laravel-ip-blocker. Do not edit manually.';

    public function __construct(
        private readonly string $serverType = 'nginx',
        private readonly string $denyPath = '/etc/nginx/conf.d/blocked-ips.conf',
        private readonly string $reloadCommand = 'nginx -s reload',
        private readonly string $allowOverridePath = '/var/www/html/.htaccess',
    ) {}

    /**
     * Generate a deny configuration for the web server.
     *
     * @param array<int, string> $ips List of IP addresses to block.
     * @return bool True on success, false on failure.
     */
    public function generate(array $ips): bool
    {
        $activeIps = BlockedIp::active()->pluck('ip')->toArray();

        $uniqueIps = array_unique(array_merge($activeIps, $ips));

        sort($uniqueIps);

        Log::info('[DenyGenerator.generate] Generating deny config', [
            'server_type' => $this->serverType,
            'deny_path' => $this->serverType === 'nginx' ? $this->denyPath : $this->allowOverridePath,
            'ips_count' => count($uniqueIps),
        ]);

        $content = $this->serverType === 'nginx'
            ? $this->generateNginxConfig($uniqueIps)
            : $this->generateApacheConfig($uniqueIps);

        $targetPath = $this->serverType === 'nginx' ? $this->denyPath : $this->allowOverridePath;

        try {
            $dir = dirname($targetPath);
            if (! is_dir($dir)) {
                mkdir($dir, 0755, true);
                Log::debug('[DenyGenerator.generate] Created directory', [
                    'path' => $dir,
                ]);
            }

            $written = file_put_contents($targetPath, $content, LOCK_EX);

            if ($written === false) {
                Log::error('[DenyGenerator.generate] Failed to write config file', [
                    'path' => $targetPath,
                ]);

                return false;
            }

            Log::info('[DenyGenerator.generate] Config file written', [
                'path' => $targetPath,
                'bytes' => $written,
            ]);

            return $this->reloadServer();
        } catch (\Throwable $e) {
            Log::error('[DenyGenerator.generate] Error generating config', [
                'path' => $targetPath,
                'error' => $e->getMessage(),
            ]);

            return false;
        }
    }

    /**
     * Reload the web server.
     */
    private function reloadServer(): bool
    {
        Log::info('[DenyGenerator.reloadServer] Reloading server', [
            'command' => $this->reloadCommand,
        ]);

        $output = [];
        $exitCode = 0;

        exec($this->reloadCommand, $output, $exitCode);

        if ($exitCode === 0) {
            Log::info('[DenyGenerator.reloadServer] Server reloaded successfully');
        } else {
            Log::error('[DenyGenerator.reloadServer] Server reload failed', [
                'exit_code' => $exitCode,
                'output' => implode("\n", $output),
            ]);
        }

        return $exitCode === 0;
    }

    /**
     * Generate nginx deny configuration.
     *
     * @param array<int, string> $ips
     */
    private function generateNginxConfig(array $ips): string
    {
        $lines = [
            self::HEADER,
            '# Generated: '.now()->toIso8601String(),
            "# Total blocked IPs: ".count($ips),
            '',
        ];

        foreach ($ips as $ip) {
            $lines[] = "deny {$ip};";
        }

        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * Generate Apache deny configuration (.htaccess or conf).
     *
     * @param array<int, string> $ips
     */
    private function generateApacheConfig(array $ips): string
    {
        $lines = [
            self::HEADER,
            '# Generated: '.now()->toIso8601String(),
            "# Total blocked IPs: ".count($ips),
            '',
            '<Limit GET POST PUT PATCH DELETE>',
        ];

        foreach ($ips as $ip) {
            $lines[] = "    Require not ip {$ip}";
        }

        $lines[] = '</Limit>';
        $lines[] = '';

        return implode("\n", $lines);
    }
}
